-- 판매가(PRODUCT) * 판매량(OFFLINE_SALE)
-- 매출액 DESC / 상품코드 ASC
-- 판매가(PRODUCT) * 판매량(OFFLINE_SALE)
-- 매출액 DESC / 상품코드 ASC
SELECT
    P.PRODUCT_CODE,
    SUM(O.SALES_AMOUNT * P.PRICE) AS SALES
FROM
    PRODUCT P
INNER JOIN
    OFFLINE_SALE O
ON
    P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    SALES DESC, 
    P.PRODUCT_CODE ASC; 
