-- 판매가(PRODUCT) * 판매량(OFFLINE_SALE)
-- 매출액 DESC / 상품코드 ASC
SELECT P.PRODUCT_CODE,  SUM(OFF.SALES_AMOUNT) * P.PRICE AS SALES
FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS OFF
ON P.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;