-- 1. 자동차 종류 "세단" 또는 "SUV"인 자동차 중
-- 2. 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 3. 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
-- 대여 금액 DESC , 자동차 종류 ASC , 자동차 ID DESC

-- SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * 30 - (1-D.DISCOUNT_RATE * 0.01))) AS FEE
-- FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
-- WHERE C.CAR_TYPE IN ('세단', 'SUV')
-- AND D.DURATION_TYPE = '30일 이상'
-- AND C.CAR_TYPE = D.CAR_TYPE
-- AND (C.DAILY_FEE * 30 - (1-D.DISCOUNT_RATE * 0.01)) BETWEEN 500000 AND 2000000
-- AND C.CAR_ID NOT IN (
--     SELECT CAR_ID
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--     WHERE end_date >= TO_DATE('2022-11-01','YYYY-MM-DD')
-- )
-- ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE* 30* (1-D.DISCOUNT_RATE*0.01) ) AS FEE
  from  CAR_RENTAL_COMPANY_CAR C , CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
  where C.car_type in ('세단','SUV') 
    AND D.DURATION_TYPE = '30일 이상'
    AND C.car_type = D.car_type
    AND (C.DAILY_FEE* 30* (1-D.DISCOUNT_RATE*0.01) ) BETWEEN 500000 AND 2000000
    and car_id  NOT in
      (select CAR_ID        
         from CAR_RENTAL_COMPANY_RENTAL_HISTORY  
        where end_date >= TO_DATE('2022-11-01','YYYY-MM-DD')
      )
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC