-- 생산일자 2022/05 식품ID, 식품이름, 총매출(내림차순) 조회 / 총매출 같으면 ID ASC
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS 총매출
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN TO_DATE('20220501', 'YYYY-MM-DD') AND TO_DATE('20220531', 'YYYY-MM-DD')
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 총매출 DESC, P.PRODUCT_ID ASC;