SELECT FLAVOR FROM (
    SELECT A.FLAVOR AS FLAVOR , A.TOTAL_ORDER + B.TOTAL_ORDER AS TOTAL_ORDER FROM(
        SELECT FLAVOR , SUM(TOTAL_ORDER)
        AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) A
    LEFT JOIN FIRST_HALF B
    ON A.FLAVOR = B.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)
WHERE ROWNUM <=3