SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS 총거래금액
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY 총거래금액 ASC;