-- 시간대별 입양 몇 건 발생했는지 count (09시 ~ 19:59 까지)
-- 결과는 시간대 순으로 정렬
-- HOUR(DATETIME)을 HOUR로 지정!
SELECT HOUR(DATETIME) AS 'HOURS', COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE 
    HOUR(DATETIME) >= 9
    AND HOUR(DATETIME) < 20
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY HOUR(DATETIME)