-- 시간대별 입양 몇 건 발생했는지 count
-- 결과는 시간대 순으로 정렬
-- HOUR(DATETIME)을 HOUR로 지정!
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR>=9 AND HOUR <= 19
ORDER BY HOUR;